<?php

namespace POC\AareonBundle\Repository;

use POC\AareonBundle\Entity\Team;
use Doctrine\ORM\EntityRepository;

/**
 * TeamRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TeamRepository extends EntityRepository
{

    public function getAllTeamsSortedByDescBudget()
    {
        $q = $this->createQueryBuilder('t')->orderBy('t.budget', 'DESC');

        return $q->getQuery()->getResult();
    }
}
